In [1]:
import numpy as np
import random
from src.genetic import AGene

In [2]:
g1 = AGene()
g2 = AGene()

In [3]:
print(g1.string.astype(int))
print(g2.string.astype(int))

[0 1 1 0 1 1 0 1 1 0 0 1 1 1 0 0 0 0 0 1 1 0 0 1 1 1 1 0 1 0]
[1 1 1 1 0 0 1 0 0 0 0 1 0 0 1 1 0 0 1 0 1 0 1 1 1 0 1 1 0 1]


In [4]:
g3, g4 = g1*g2

In [9]:
print(g3.string.astype(int))
print(g3.mutate().string.astype(int))

[0 1 1 0 1 1 0 1 1 0 0 1 1 1 0 0 0 0 0 1 1 0 0 1 1 1 1 1 0 1]
[0 1 1 0 1 1 1 1 1 0 0 1 1 1 0 0 0 0 0 1 1 0 0 1 1 1 1 1 0 1]


In [12]:
print(g4.string[20:])
g4.encode()

[ True False  True  True  True False  True False  True False]


(313423, 349)